- hosts: hanatraining 
  gather_facts: false
  tasks:   
  - name: SAP HANA databases
    become: yes
    args:
      warn: false
    become_user: "hxeadm"
    #shell: "/usr/sap/SH1/HDB00/HDB info|grep -i 'hdbnameserver'"
    shell: "/usr/sap/{{hana_sid}}/HDB{{instance_number}}/exe/hdbsql  -A -x -d SYSTEMDB -U {{hdb_key}} \"select * from m_databases\""
    register: hdbstatus
  - debug: 
      msg: "{{hdbstatus.stdout.split('\n')}}"