- hosts: hanatraining 
  gather_facts: false
  tasks:   
  - name: SAP HANA Service Status
    become: yes
    become_user: "hxeadm"
    #shell: "/usr/sap/SH1/HDB00/HDB info|grep -i 'hdbnameserver'"
    shell: "/usr/sap/{{hana_sid}}/HDB{{instance_number}}/HDB info"
    register: hdbstatus
  - debug: 
      msg: "{{hdbstatus.stdout.split('\n')}}"