- hosts: hanatraining 
  gather_facts: false
  vars:
    instance_number: "90"
    hana_sid: "HXE"
  tasks:   
  - name: SAP HANA Version
    become: yes
    args:
      warn: false
    become_user: "hxeadm"
    #shell: "/usr/sap/SH1/HDB00/HDB info|grep -i 'hdbnameserver'"
    shell: "/usr/sap/{{hana_sid}}/HDB{{instance_number}}/HDB version"
    register: hdbstatus
  - debug: 
      msg: "{{hdbstatus.stdout.split('\n')}}"